# This workflow restarts your bot whenever you merge into the branch called 'main'
name: Deploy
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Checks:
    runs-on: self-hosted
    steps:
      - name: Close existing process
        run: |
          pkill -9 -f script.py
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Venv
        run: pip install virtualenv
      - name: Activate Venv
        run: virtualenv venv
      - run: source venv/bin/activate
      - name: Install packages
        run: pip install -r requirements.txt
      - name: Perform restart
        run: |
          python bot.py
    
